version: "3.8"

services:
  go:
    build: ./src/go
    volumes:
      - ./src/go:/app
    # Se ejecuta el comando por defecto (CMD) definido en el Dockerfile
    command: go test -v ./tests

  python:
    build: ./src/python
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      # Monta la raíz para preservar la estructura relativa (assets, etc.)
      - ./:/app
    # Se ejecuta el comando por defecto definido en el Dockerfile (pytest)
    command: pytest
