version: "3.8"

services:
  go:
    build: ./src/go
    volumes:
      - ./src/go:/app
    command: go test -v ./tests/unit/  # 🔹 Ejecuta solo los tests unitarios de Go

  python:
    build: ./src/python
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      - ./:/app
    command: pytest src/python/tests/unit/  # 🔹 Ejecuta solo los tests unitarios de Python


  integration_python_pub:
    build: ./src/python
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      - ./src/python:/app
      - ./assets:/assets
      - ./shared:/shared
    command: python3 tests/integration/main_publisher.py

  integration_go_sub:
    build: ./src/go
    volumes:
      - ./src/go:/app
      - ./assets:/assets
      - ./shared:/shared
    command: go run /app/tests/integration/main_subscriber.go


  integration_go_pub:
    build: ./src/go
    volumes:
      - ./src/go:/app
      - ./shared:/shared
    command: go run /app/tests/integration/main_publisher.go

  integration_python_sub:
    build: ./src/python
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      - ./src/python:/app
      - ./shared:/shared
    command: python3 tests/integration/main_subscriber.py


