version: "3.8"

services:
  go:
    image: golang:1.13
    working_dir: /app
    volumes:
      - ./src/go:/app
    command: sh -c "apt-get update && apt-get install -y libzmq3-dev && go test -v ./tests"
  
  python:
    image: python:3.8
    working_dir: /app/src/python
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      - ./:/app
    command: sh -c "apt-get update && apt-get install -y libgl1-mesa-glx && pip install --no-cache-dir -r requirements.txt && pytest"
