version: "3.8"

services:
  go:
    build: ./src/go
    image: go_pubsub:latest
    volumes:
      - ./src/go:/app
    command: go test -v ./tests/unit/  # 🔹 Ejecuta solo los tests unitarios de Go

  python:
    build: ./src/python
    image: python_pubsub:latest
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      - ./:/app
    command: pytest src/python/tests/unit/  # 🔹 Ejecuta solo los tests unitarios de Python


  integration_python_pub:
    image: python_pubsub:latest
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      - ./src/python:/app
      - ./assets:/assets
      - ./shared:/shared
    command: python3 tests/integration/main_publisher.py

  integration_python_sub:
    image: python_pubsub:latest
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/python
    volumes:
      - ./src/python:/app
      - ./shared:/shared
    command: python3 tests/integration/main_subscriber.py

  integration_go_sub:
    image: go_pubsub:latest
    volumes:
      - ./src/go:/app
      - ./assets:/assets
      - ./shared:/shared
    command: go run /app/tests/integration/main_subscriber.go


  integration_go_pub:
    image: go_pubsub:latest
    volumes:
      - ./src/go:/app
      - ./shared:/shared
    command: go run /app/tests/integration/main_publisher.go



  cpp_build:
    build: ./src/cpp
    image: cpp_pubsub:latest 
    volumes:
      - ./src/cpp:/app
      - ./shared:/shared
    command: sh -c "rm -rf build && mkdir -p build && cd build && cmake .. && make"


  cpp_unit_tests:
    image: cpp_pubsub:latest
    volumes:
      - ./shared:/shared
    depends_on:
      - cpp_build
    command: sh -c "cd /app/build && ctest --output-on-failure"

  integration_cpp_pub:
    image: cpp_pubsub:latest
    volumes:
      - ./shared:/shared
    depends_on:
      - cpp_build
    command: /app/build/main_publisher

  integration_cpp_sub:
    image: cpp_pubsub:latest
    volumes:
      - ./shared:/shared
    depends_on:
      - cpp_build
    command: /app/build/main_subscriber
